# Generated by Django 6.0.1 on 2026-02-03 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GAS', 'Gas')], max_length=20)),
                ('month', models.DateField(help_text='Billing month (use first day of month)')),
                ('units_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='app.customer')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('customer', 'utility_type', 'month')},
            },
        ),
    ]
