# Generated by Django 6.0.1 on 2026-02-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_meterreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GAS', 'Gas')], max_length=20)),
                ('min_units', models.IntegerField()),
                ('max_units', models.IntegerField()),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'tariff',
                'ordering': ['utility_type', 'min_units'],
            },
        ),
    ]
