# Generated by Django 6.0.1 on 2026-02-10 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_type',
            new_name='utility_type',
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
