# Generated by Django 6.0.1 on 2026-02-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_staff_type_staff_utility_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
