# Generated by Django 6.0.1 on 2026-02-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tariff_penalty_amount_tariff_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
